---
- name : clone pcl_apps
  git:
    repo: https://github.com/OUXT-Polaris/pcl_apps.git
    dest: ../robotx_ws/src/perception/pcl_apps
    version: master
    accept_hostkey: yes
- name : clone pointcloud_to_laserscan
  git:
    repo: https://github.com/OUXT-Polaris/pointcloud_to_laserscan.git
    dest: ../robotx_ws/src/perception/pointcloud_to_laserscan
    version: eloquent-devel
    accept_hostkey: yes
- name : clone scan_segmentation
  git:
    repo: https://github.com/OUXT-Polaris/scan_segmentation
    dest: ../robotx_ws/src/perception/scan_segmentation
    version: master
    accept_hostkey: yes
- name : clone hermite_path_planner
  git:
    repo: https://github.com/OUXT-Polaris/hermite_path_planner.git
    dest: ../robotx_ws/src/planning/hermite_path_planner
    version: master
    accept_hostkey: yes
- name: clone behavior_tree_action_builder
  git:
    repo: https://github.com/OUXT-Polaris/behavior_tree_action_builder.git
    dest: ../robotx_ws/src/planning/behavior_tree_action_builder
    version: master
    accept_hostkey: yes
- name: clone robotx_behavior_tree
  git:
    repo: https://github.com/OUXT-Polaris/robotx_behavior_tree.git
    dest: ../robotx_ws/src/planning/robotx_behavior_tree
    version: master
    accept_hostkey: yes
- name: clone robotx_bt_planner
  git:
    repo: https://github.com/OUXT-Polaris/robotx_bt_planner.git
    dest: ../robotx_ws/src/planning/robotx_bt_planner
    version: master
    accept_hostkey: yes
- name: clone color_names
  git:
    repo: https://github.com/OUXT-Polaris/color_names.git
    dest: ../robotx_ws/src/utils/color_names
    version: master
    accept_hostkey: yes
- name: clone quaternion_operation
  git:
    repo: https://github.com/OUXT-Polaris/quaternion_operation.git
    dest: ../robotx_ws/src/utils/quaternion_operation
    version: ros2
    accept_hostkey: yes
- name: clone data_buffer
  git:
    repo: https://github.com/OUXT-Polaris/data_buffer.git
    dest: ../robotx_ws/src/utils/data_buffer
    version: ros2
    accept_hostkey: yes
- name: clone geometry_msgs_data_buffer
  git:
    repo: https://github.com/OUXT-Polaris/geometry_msgs_data_buffer.git
    dest: ../robotx_ws/src/utils/geometry_msgs_data_buffer
    version: ros2
    accept_hostkey: yes
- name: clone velodyne
  git:
    repo: https://github.com/ros-drivers/velodyne.git
    dest: ../robotx_ws/src/drivers/velodyne
    version: dashing-devel
    accept_hostkey: yes
- name: clone nmea_msgs
  git:
    repo: https://github.com/ros-drivers/nmea_msgs.git
    dest: ../robotx_ws/src/drivers/nmea_msgs
    version: ros2
    accept_hostkey: yes
- name: clone nmea_gps_driver
  git:
    repo: https://github.com/OUXT-Polaris/nmea_gps_driver.git
    dest: ../robotx_ws/src/drivers/nmea_gps_driver
    version: master
    accept_hostkey: yes
- name: clone wamv_description
  git:
    repo: https://github.com/OUXT-Polaris/wamv_description.git
    dest: ../robotx_ws/src/description/wamv_description
    version: master
    accept_hostkey: yes
- name: clone nmea_to_geopose
  git:
    repo: https://github.com/OUXT-Polaris/nmea_to_geopose.git
    dest: ../robotx_ws/src/pf_localization/nmea_to_geopose
    version: ros2
    accept_hostkey: yes
- name: clone pf_localization
  git:
    repo: https://github.com/OUXT-Polaris/pf_localization.git
    dest: ../robotx_ws/src/pf_localization/pf_localization
    version: ros2
    accept_hostkey: yes 
- name: clone odom_frame_publisher
  git:
    repo: https://github.com/OUXT-Polaris/odom_frame_publisher.git
    dest: ../robotx_ws/src/odom_frame_publisher/odom_frame_publisher
    version: ros2
    accept_hostkey: yes
