name: robotx_setup

on:
  schedule:
  - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: setup
        runs-on: ubuntu-18.04
        steps:
            - name: basic install
              run: |
                  sudo apt install make ansible
            - name: ansible version
              run: |
                   ansible-playbook --version
            - uses: actions/checkout@v2-beta
            - name: ansible
              run: |
                  ansible-playbook -i ansible/hosts/localhost.ini ansible/setup_full.yml --connection local --become
            - name: Slack Notification on Success
              if: success()
              uses: rtCamp/action-slack-notify@v2.0.2
              env:
                SLACK_CHANNEL: ci
                SLACK_TITLE: Test Success
                SLACK_COLOR: good
            - name: Slack Notification on Failure
              uses: rtCamp/action-slack-notify@v2.0.2
              if: failure()
              env:
                SLACK_CHANNEL: ci
                SLACK_TITLE: Test Failure
                SLACK_COLOR: danger
