name: robotx_setup

on: [push, pull_request]

jobs:
    job1:
        name: setup
        runs-on: ubuntu-18.04
        steps:
            - name: basic install
              run: |
                  sudo apt install make ansible
            - name: ansible version
              run: |
                   ansible-playbook --version
            - uses: actions/checkout@v2-beta
            - name: ansible
              run: |
                  ansible-playbook -i ansible/hosts/hosts.ini ansible/setup_full.yml --connection local --become
