name: robotx_setup

on:
  schedule:
  - cron: 0 0 * * *
  push:

jobs:
    job1:
        name: setup
        runs-on: ubuntu-18.04
        steps:
            - name: basic install
              run: |
                  sudo apt install make ansible
            - name: ansible version
              run: |
                   ansible-playbook --version
            - uses: actions/checkout@v2-beta
            - name: ansible
              run: |
                  ansible-playbook -i ansible/hosts/localhost.ini ansible/setup_full.yml --connection local --become
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v1
            - name: Slack Notification
              uses: 8398a7/action-slack@v2
              with:
                status: ${{ job.status }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
